[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
